/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Task Tracker Api
 * OpenAPI spec version: 1.0
 */

export interface CreateProjectDto {
  assignedUsers: string[];
  description: string;
  endDate: string;
  name: string;
  startDate: string;
  status: string;
}
