/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Task Tracker Api
 * OpenAPI spec version: 1.0
 */
import type { UsersOnProjects } from "./usersOnProjects";
import type { Task } from "./task";

export interface Project {
  assignedUsers?: UsersOnProjects[];
  createdAt: string;
  description: string;
  endDate: string;
  id: string;
  name: string;
  startDate: string;
  status: string;
  tasks?: Task[];
  updatedAt: string;
}
