/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Task Tracker Api
 * OpenAPI spec version: 1.0
 */
import type { RegisterDtoRole } from "./registerDtoRole";

export interface RegisterDto {
  email: string;
  firstName: string;
  lastName: string;
  password: string;
  role?: RegisterDtoRole;
}
