/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Task Tracker Api
 * OpenAPI spec version: 1.0
 */
import type { UserDto } from "./userDto";

export interface SessionDto {
  accessToken: string;
  refreshToken: string;
  user: UserDto;
}
