/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Task Tracker Api
 * OpenAPI spec version: 1.0
 */

export interface TaskDto {
  createdAt: string;
  description: string;
  endDate: string;
  id: string;
  name: string;
  priority: string;
  projectId: string;
  startDate: string;
  status: string;
  updatedAt: string;
}
