/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Task Tracker Api
 * OpenAPI spec version: 1.0
 */
import type { UsersOnTasks } from "./usersOnTasks";
import type { Project } from "./project";

export interface Task {
  assignedUsers?: UsersOnTasks[];
  createdAt: string;
  description: string;
  endDate: string;
  id: string;
  name: string;
  priority: string;
  project?: Project;
  projectId: string;
  startDate: string;
  status: string;
  updatedAt: string;
}
