/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Task Tracker Api
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserDtoRole } from "./updateUserDtoRole";

export interface UpdateUserDto {
  email?: string;
  firstName?: string;
  lastName?: string;
  role?: UpdateUserDtoRole;
}
