/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Task Tracker Api
 * OpenAPI spec version: 1.0
 */
import type { UserDtoRole } from "./userDtoRole";

export interface UserDto {
  createdAt: string;
  email: string;
  firstName: string;
  id: string;
  lastName: string;
  role: UserDtoRole;
  updatedAt: string;
}
