/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Task Tracker Api
 * OpenAPI spec version: 1.0
 */
import type { Project } from "./project";
import type { User } from "./user";

export interface UsersOnProjects {
  createdAt: string;
  project?: Project;
  projectId: string;
  updatedAt: string;
  user?: User;
  userId: string;
}
