/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Task Tracker Api
 * OpenAPI spec version: 1.0
 */
import type { Task } from "./task";
import type { User } from "./user";

export interface UsersOnTasks {
  createdAt: string;
  task?: Task;
  taskId: string;
  updatedAt: string;
  user?: User;
  userId: string;
}
