/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Task Tracker Api
 * OpenAPI spec version: 1.0
 */
import type { UsersOnProjects } from "./usersOnProjects";
import type { UsersOnTasks } from "./usersOnTasks";
import type { UserRole } from "./userRole";

export interface User {
  assignedProjects?: UsersOnProjects[];
  assignedTasks?: UsersOnTasks[];
  createdAt: string;
  email: string;
  firstName: string;
  id: string;
  lastName: string;
  role: UserRole;
  updatedAt: string;
}
